import type { Audit, AuditAnswer } from "@/lib/types";

export const mockAudits: Audit[] = [
  {
    $id: "mock-audit-cal1",
    id: "mock-audit-cal1",
    zoneId: "cal1",
    zoneName: "CAL1",
    auditorName: "Equipe ED",
    shift: "Matin",
    scorePercent: 86,
    status: "conforme",
    createdAt: "2026-06-12T08:30:00.000Z",
  },
  {
    $id: "mock-audit-m3",
    id: "mock-audit-m3",
    zoneId: "m3",
    zoneName: "M3",
    auditorName: "Equipe ED",
    shift: "Soir",
    scorePercent: 67,
    status: "a_surveiller",
    createdAt: "2026-06-05T16:45:00.000Z",
  },
];

export const mockAuditAnswers: Record<string, AuditAnswer[]> = {
  "mock-audit-cal1": [
    {
      $id: "mock-answer-cal1-trier",
      id: "mock-answer-cal1-trier",
      auditId: "mock-audit-cal1",
      criterionLabel: "Trier",
      score: 5,
      comment: "Poste degage, aucun element inutile visible.",
      hasGap: false,
    },
    {
      $id: "mock-answer-cal1-ranger",
      id: "mock-answer-cal1-ranger",
      auditId: "mock-audit-cal1",
      criterionLabel: "Ranger",
      score: 4,
      comment: "Marquages presents, quelques consommables a recentrer.",
      hasGap: false,
    },
    {
      $id: "mock-answer-cal1-nettoyer",
      id: "mock-answer-cal1-nettoyer",
      auditId: "mock-audit-cal1",
      criterionLabel: "Nettoyer",
      score: 4,
      comment: "Zone propre.",
      hasGap: false,
    },
    {
      $id: "mock-answer-cal1-standardiser",
      id: "mock-answer-cal1-standardiser",
      auditId: "mock-audit-cal1",
      criterionLabel: "Standardiser",
      score: 4,
      comment: "Standards visibles.",
      hasGap: false,
    },
    {
      $id: "mock-answer-cal1-maintenir",
      id: "mock-answer-cal1-maintenir",
      auditId: "mock-audit-cal1",
      criterionLabel: "Maintenir",
      score: 4,
      comment: "Routine suivie.",
      hasGap: false,
    },
  ],
  "mock-audit-m3": [
    {
      $id: "mock-answer-m3-trier",
      id: "mock-answer-m3-trier",
      auditId: "mock-audit-m3",
      criterionLabel: "Trier",
      score: 3,
      comment: "Elements en attente a identifier.",
      hasGap: true,
    },
    {
      $id: "mock-answer-m3-ranger",
      id: "mock-answer-m3-ranger",
      auditId: "mock-audit-m3",
      criterionLabel: "Ranger",
      score: 3,
      comment: "Rangements partiellement respectes.",
      hasGap: true,
    },
    {
      $id: "mock-answer-m3-nettoyer",
      id: "mock-answer-m3-nettoyer",
      auditId: "mock-audit-m3",
      criterionLabel: "Nettoyer",
      score: 4,
      comment: "Nettoyage correct.",
      hasGap: false,
    },
    {
      $id: "mock-answer-m3-standardiser",
      id: "mock-answer-m3-standardiser",
      auditId: "mock-audit-m3",
      criterionLabel: "Standardiser",
      score: 3,
      comment: "Standard a remettre a jour.",
      hasGap: true,
    },
    {
      $id: "mock-answer-m3-maintenir",
      id: "mock-answer-m3-maintenir",
      auditId: "mock-audit-m3",
      criterionLabel: "Maintenir",
      score: 4,
      comment: "Suivi hebdomadaire present.",
      hasGap: false,
    },
  ],
};
